#!/bin/sh
if [ "$#" = "0" ]; then
  echo 'Usage: ispmail u[ser]|d[omain]|a[lias] add|change|remove|list help|<argslist>'
else
  if [ "$1" = "user"  ] || [  "$1" = "u" ]; then
    if [ "$2" = "add" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "4" ]; then
        echo 'Usage: ispmail user add john.doe@exmaple.com password1234'
      else
        virtual_domain=$(echo "$3" | perl -pe 's/.*?@(.*)/\1/')
        virtual_domain_id=$(mysql -s -e "SELECT id FROM virtual_domains WHERE name='$virtual_domain'" mailserver)
        if [ "$virtual_domain_id" = '' ]; then
          echo "The domain $virtual_domain does not exist, please create it before assigning users to it"
        else
          echo "Adding user with email $3 and password $4 on virtual domain $virtual_domain with id $virtual_domain_id"
          mysql -e "INSERT INTO virtual_users (domain_id, email, password) VALUES ( $virtual_domain_id,'$3',CONCAT('{SHA256-CRYPT}', ENCRYPT ('$4', CONCAT('\$5\$', SUBSTRING(SHA(RAND()), -16)))));" mailserver
        fi
      fi
    elif [ "$2" = "list" ]; then
      mysql -e "SELECT * FROM virtual_users" mailserver
    elif [ "$2" = "change" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "4" ]; then
        echo 'Usage: ispmail user change john.doe@exmaple.com newPassword1234'
      else
        mysql -e "UPDATE virtual_users SET password=CONCAT('{SHA256-CRYPT}', ENCRYPT ('$4', CONCAT('\$5\$', SUBSTRING(SHA(RAND()), -16)))) WHERE email='$3';" mailserver
      fi
    elif [ "$2" = "remove" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "3" ] ; then
        echo 'Usage: ispmail user remove john.doe@exmaple.com'
      else
        mysql -e "DELETE FROM virtual_users WHERE email='$3';" mailserver
      fi
    else
      echo 'Usage: ispmail user add|remove|change|list help|<argslist>'
    fi
  elif [ "$1" = "domain"  ] || [  "$1" = "d" ]; then
    if [ "$2" = "add" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "3" ]; then
        echo 'Usage: ispmail domain add exmaple.com'
      else
        mysql -e "INSERT INTO virtual_domains (name) VALUES ('$3');" mailserver
      fi
    elif [ "$2" = "remove" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "3" ]; then
        echo 'Usage: ispmail domain remove example.com'
      else
        mysql -e "DELETE FROM virtual_domains WHERE name='$3'" mailserver
      fi
    elif [ "$2" = "list" ]; then
      mysql -e "SELECT * FROM virtual_domains" mailserver
    else
      echo 'Usage: ispmail domain add|remove|list help|<argslist>'
    fi
elif [ "$1" = "alias"  ] || [  "$1" = "a" ]; then
    echo 'Warning: Destination emails are not checked, beware of typos!'
    echo 'Feel free to use catchall aliases: ispmail alias add @example.com admin@example.com'
    if [ "$2" = "add" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "4" ]; then
        echo 'Usage: ispmail alias add source.address@example.com destination.address@example.com'
     else
        virtual_domain=$(echo "$3" | perl -pe 's/.*?@(.*)/\1/')
        virtual_domain_id=$(mysql -s -e "SELECT id FROM virtual_domains WHERE name='$virtual_domain'" mailserver)
        if [ "$virtual_domain_id" = '' ]; then
          echo "The domain $virtual_domain does not exist, please create it before assigning aliases to it"
        else
          echo "Adding alias with source $3 and destination $4 on virtual domain $virtual_domain with id $virtual_domain_id"
          mysql -e "INSERT INTO virtual_aliases (domain_id, source, destination) VALUES ('$virtual_domain_id', '$3', '$4');" mailserver
        fi
      fi
    elif [ "$2" = "remove" ]; then
      if [ "$3" = "help" ] || [ "$#" -ne "3" ]; then
        echo 'Usage: ispmail alias remove source.adress@example.com'
      else
        mysql -e "DELETE FROM virtual_aliases WHERE source='$3'" mailserver
      fi
    elif [ "$2" = "list" ]; then
      mysql -e "SELECT * FROM virtual_aliases" mailserver
    else
      echo 'Usage: ispmail alias add|remove|list help|<argslist>'
    fi
  else
    echo 'Usage: ispmail u[ser]|d[omain]|a[lias] add|change|remove|list help|<argslist>'
  fi
fi
